baseURL = 'https://bytesizebrews.com/'
languageCode = 'en-us'
title = 'ByteSizeBrews'
theme = 'Niello'

[languages]
	[languages.en]
		title = "{CodeTrace} - Discover Issues, Share Solutions."
		languageCode = "en-us"
		LanguageName = "🇺🇸EN"
		contentDir = "content/en"
		weight = 1
		[[languages.en.menus.main]]
			name = 'Home'
			pageRef = '/'
			weight = 1
		[[languages.en.menus.main]]
			name = 'Categories'
			pageRef = '/categories'
			weight = 2
		[[languages.en.menus.main]]
			name = 'Tags'
			pageRef = '/tags'
			weight = 3

[params]
[params.bannershowcase]
	categories = ["SoftSkills"]
	limit = 2
[params.email]
	contact = "bytesizebrews@gmail.com"
[params.ignore]
	categories = ["privacy", "terms", "archives", "cookie"]
[params.categoryImages]
  softskills = "/image/categories/softskills_robots.png"